services:
  stupid-bot:
    image: ghcr.io/xiaoxuxxxx/stupid-bot
    container_name: stupid-bot
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    env_file:
      - .env
    restart: unless-stopped
