name: Renovate

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@v43.0.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
