name: update-yt-dlp

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Renovate bot
        uses: renovatebot/github-action@v43.0.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
